### PR TITLE
fix how nullability is handled + minor fixes

### LINKED ISSUE #41: Correct the handling of nullable
Try to avoid "!" compilator bypass.
This issue is related withcode related to #39

### PR DESCRIPTION
**Pull request by zetTtai**
Close #41

### CODE REVIEW

File: src/Application/Sheets/Commands/DeleteSheet/DeleteSheet.cs [hunk 1]
```diff
@@ -21,18 +22,23 @@ public class DeleteSheetCommandHandler(
 
     public async Task<Response> Handle(DeleteSheetCommand request, CancellationToken cancellationToken)
     {
+        Debug.Assert(_user.Id is not null, "User ID should never be null here due to middleware check.");
```
Comment (KiyanDev) [inline src/Application/Sheets/Commands/DeleteSheet/DeleteSheet.cs:26]: ?

File: src/Application/Sheets/Queries/GetSheetById/GetSheetById.cs [hunk 2]
```diff
@@ -30,19 +34,22 @@ public async Task<Response<SheetVm>> Handle(GetSheetByIdQuery request, Cancellat
...
         .FirstOrDefaultAsync(s => s.Id == request.Id, cancellationToken);
 
-        var response = await _authorizationService.ValidateEntityAccess<SheetVm>(sheet, _user.Id!);
+        if (sheet is null)
+        {
+            return Response<SheetVm>.Failure(HttpStatusCode.NotFound, [$"Sheet with ID {request.Id} not found."]);
+        }
 
-        if (response is not null)
+        if (!await _authorizationService.IsOwner(sheet, _user.Id))
```
Comment (KiyanDev) [inline src/Application/Sheets/Queries/GetSheetById/GetSheetById.cs]: extract into variable

File: src/Application/Sheets/Commands/DeleteSheet/DeleteSheet.cs (hunk 1 above)
Comment (zetTtai) [reply src/Application/Sheets/Commands/DeleteSheet/DeleteSheet.cs:26]: comment for the future: Its a way to avoid the error of _user.Id being null because its impossible as the error message said
